version: "3"
services:

  pytest:
    build: .
    # volumes:
    #   - ${PWD}:/home/pytest
    # working_dir: /home/pytest
    stdin_open: true
    tty: true
    # env_file: .env
    privileged: true
    # command: ./exec_test.sh
    ports:
      - "4443:4444"
    links:
        - "webdriver: chromium"

    
  chromium:
    image: seleniarm/standalone-chromium:latest
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
